#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Föreläsningens 'Var vi krockar' -> steelmannad knivskarp prosa (VERKTYGET/manifest).
Boken forklara-ai.html synkas separat i ett ordnat svep när alla kärn- + extrakort är klara.
Kör om med fler kort i K allteftersom."""
import json, re, io
ROOT="/Users/ainnova/Projects/forklara-ai/"
K={
# --- 000 ---
"vem-ar-jag":'Fråga vem som borde få uttala sig om AI, så delar sig rummet — och det säger något om vad vi tror kunskap är. Den ena litar på experten med djup i ämnet. Den andra på den som lever med tekniken varje dag och ser vad den gör med vanligt folk. Krocken: sitter rätten att tala i djupet eller i erfarenheten — och vad missar vi om vi bara lyssnar på det ena?',
"vem-bildar-oss":'Fråga vem som borde bilda oss, så skiljer sig blickarna — mellan världsdelar och tvärs genom samma kök. Den ena vill värna de gamla källorna: läraren, boken, samtalet. Den andra ser att barnbarnet redan formas mer av flödet än av far. Krocken: ska vi försvara de gamla bildarna eller lära oss styra de nya — och hinner vi välja innan valet är gjort åt oss?',
"dummare-eller-smartare":'Alla är överens om att något står på spel — men inte om vad man ska göra. Den ena ser en utvidgad hjärna: verktyg har alltid gjort oss kapablare, det här är nästa steg. Den andra ser en avlastad hjärna som slutar öva det den lämnar bort. Krocken: gör tekniken oss dummare eller smartare — eller är det vi som avgör, beroende på om vi lutar oss mot den eller bryner oss mot den?',
"starka-kanslor":'Samma teknik, helt olika platser att stå på — och därför helt olika känslor. Den ena vill sakta ner inför en kraft vi inte förstår. Den andra vill skynda på mot allt gott den kan göra. Båda drivs av omtanke om samma framtid. Krocken: är den största faran att gå för fort, eller att gå för långsamt medan andra springer?',
# --- 010 ---
"aristoteles-first-principles":'Fråga vad tänkande djupast är, så delar sig leden — och det är i själva verket AI:s stora vetenskapsstrid. Den ena ser tänkande som regler och logik, något man kan skriva ner. Den andra ser det som mönster som växer fram, omöjliga att helt fånga i regler. Krocken: är förnuftet steg att följa eller något som uppstår — och kan en maskin ha det senare?',
"vem-uppfann-ai":'Fråga vem som ska få äran, så delar sig rummet — och det säger ofta mer om berättaren än om historien. Den ena vill peka ut geniet, ögonblicket, namnet. Den andra ser en kedja av tusen händer över sekler, där ingen enskild uppfann något. Krocken: föds genombrott ur enstaka snillen eller ur ett kollektiv vi glömmer att räkna — och vem skrivs bort när vi förenklar?',
"bara-man-som-kodar":'Just den här frågan väcker starka, spretiga känslor — och det är värt att förstå varför. Den ena hör "kvot" och rycker till: talang ska avgöra, inte kön. Den andra pekar på att bilden av det ensamma manliga geniet helt enkelt är historiskt fel — de första programmerarna var kvinnor. Krocken: handlar det om att kvotera in någon, eller om att sluta kvotera bort dem som redan fanns där?',
"nar-blev-maskinen-battre":'Samma parti, men vad man ser i det skiljer sig helt. Den ena beundrar drag 37 — maskinen gjorde något ingen människa tänkt, ren skönhet. Den andra oroar sig: en maskin som optimerar mot ett mål vi satt kan hitta vägar vi aldrig menade. Krocken: är ett övermänskligt drag ett under att hylla, eller en varning om vad som händer när vi inte längre förstår hur den vann?',
"nar-blev-den-vetenskap":'Även ett genombrott alla vinner på väcker olika blickar — på vem som äger och får del av frukten. Den ena firar öppen vetenskap: kunskapen ska vara allas. Den andra ser att den som byggde den också vill, och kanske borde, få igen sin insats. Krocken: ska frukten av ett genombrott vara fri för alla eller belöna dem som bekostade det — och vad händer med nästa genombrott om vi väljer fel?',
"radsla-for-det-nya":'Samma skifte, helt olika grundton — beroende på var man står. Den ena vill stanna upp; varje ny kraft har missbrukats innan vi lärde oss tygla den. Den andra vill skynda på; varje ny kraft har också lyft fler än den skadat. Krocken: är försiktigheten det som räddar oss eller det som lämnar oss efter — och hur vet vi skillnaden i stunden?',
# --- 020 ---
"ar-ai-en-maskin":'Samma system, men vilken bild man väljer skiljer sig helt — och bilden avslöjar hållningen. Den ena säger "bara en maskin", en avancerad räknedosa utan förstånd. Den andra ser något mer organiskt, som odlats fram och överraskar sina egna byggare. Krocken: avdramatiserar "bara en maskin" det som behövs, eller blundar det för något vi faktiskt inte längre helt förstår?',
"ett-enda-foretag":'Ekosystemet är allt annat än neutralt — det dras i flera riktningar samtidigt. Den ena vill ha öppna modeller, fria för alla att bygga på. Den andra menar att de kraftfullaste systemen måste hållas stängda, för säkerheten och för att någon ska ha råd att bygga dem. Krocken: blir AI bäst och säkrast av att vara öppet för alla, eller av att några få håller i tyglarna — och vem vaktar dem då?',
"hur-larde-den-sig":'Bakom den prydliga trappan låg ett riktigt inbördeskrig om hur man ens borde bygga tänkande maskiner. Det ena laget ville skriva in reglerna för hand — logik, symboler, ordning. Det andra ville låta maskinen lära sig själv ur exempel, utan att vi säger hur. Krocken: byggs intelligens bäst uppifrån av regler vi förstår, eller nedifrån av mönster vi inte kan följa — och vad offrar vi med varje väg?',
"tokens-och-konstiga-ord":'Samma verktyg, men vad du får ut hänger på vilken bild du bär in. Den ena tror på hemliga trollformler — rätt prompt låser upp magin. Den andra ser en samtalspartner: du får ut ungefär det du orkar tänka in. Krocken: är skickligheten en uppsättning knep att lära sig, eller ett sätt att tänka klart — och vilken av dem lär dig något som består?',
"hur-snabbt-gar-utvecklingen":'Alla ser samma branta kurva — men drar helt olika slutsatser. Den ena vill skynda på; ju snabbare, desto snabbare kommer lösningarna. Den andra vill bromsa; det som växer exponentiellt hinner vi sällan förstå förrän det passerat oss. Krocken: är farten vårt hopp eller vår risk — och vem hinner sätta reglerna medan kurvan stiger?',
# --- 030 ---
"kan-man-lita-pa-den":'Hur mycket man litar på ett AI-svar drar isär oss — och det säger något om var man står. Den ena litar tills motsatsen bevisats: den har ju rätt så ofta. Den andra misstror tills det kontrollerats, för en modell kan låta lika säker när den har fel som när den har rätt. Krocken: ska tilliten vara utgångsläget, eller något svaret får förtjäna gång för gång?',
"vad-ar-sant":'Hur vi ska möta en värld full av förfalskningar drar isär oss. Den ena hoppas på tekniken — en detektor, en äkthetsstämpel som avgör vad som är sant. Den andra litar mer på den gamla mänskliga vanan: kolla källan, jämför, tvivla lite. Krocken: löser vi lögnen med bättre verktyg eller med bättre vanor — och vad händer om vi lägger allt ansvar på det ena?',
"ar-det-farligt":'Fråga vad som är farligast, så delar sig rummet — och alla bär en bit av sanningen. Den ena pekar på de nära farorna: bedrägerier, bias, övervakning, redan här. Den andra på de långsiktiga: en kraft som växer ifrån vår kontroll. Krocken: riskerar vi att stirra oss blinda på det avlägsna och missa det som skadar redan idag — eller tvärtom?',
"arver-den-vara-fordomar":'Vad man ser i en skev modell — och vad man vill göra åt det — drar isär oss. Den ena säger att AI bara speglar oss: skevheten fanns i datan, alltså i samhället. Den andra att den inte bara speglar utan förstärker, i skala och med maskinens sken av objektivitet. Krocken: är en skev modell en spegel att lära av eller en förstärkare att stoppa — och vem bär ansvaret för det den lärt sig av oss?',
"lar-eller-lurar":'Samma personliga kraft, men vad man ser i den skiljer sig helt. Den ena ser en tålmodig lärare som möter dig där du är. Den andra ser risken i just den förmågan: det som kan möta dig personligt kan också övertala dig personligt. Krocken: är en maskin som lär känna dig din bästa lärare eller din skickligaste övertalare — och märker du själv skillnaden?',
# --- 040 ---
"tar-den-mitt-jobb":'Vad AI gör med jobben ser olika ut beroende på var man står. Den ena ser automatisering: maskinen ersätter människan där den kan, och det har hänt förr. Den andra ser augmentering: maskinen tar rutinen så människan får göra det bara hon kan. Krocken: ersätter tekniken oss eller förstärker den oss — och avgörs det av tekniken själv, eller av vad vi väljer att bygga och betala för?',
"konsten-och-musiken":'Om AI-konst är "riktig konst" drar isär oss — och avslöjar vad vi tror att konst är. Den ena mäter hantverket: en maskin som blandar andras verk har inte skapat, den har härmat. Den andra mäter avsikten och mötet: om det rör någon, spelar det då roll vem som höll penseln? Krocken: sitter konsten i handen som gjorde den, eller i människan som möter den?',
"vem-ager-tiden":'Vad den vunna tiden ska bli drar isär oss — och det säger något om vad vi tror ett liv är till för. Den ena vill fylla den frigjorda tiden med mer: mer hunnet, mer producerat. Den andra vill lämna den tom med flit: tid att vara, inte bara att uträtta. Krocken: är tiden vi sparar till för att göra mer, eller för att äntligen få göra mindre?',
"mer-vad-kostar-ai-planeten":'Om AI är planetens vän eller fiende drar isär oss. Den ena ser verktyget som kan hjälpa oss lösa klimatet: bättre modeller, smartare nät. Den andra ser hur mycket energi och vatten träning och drift faktiskt drar, här och nu. Krocken: väger det AI kan spara i framtiden tyngre än det den kostar idag — och vem håller reda på båda sidor av det kvittot?',
"bilder-av-mig-deepfake":'Hur mycket vi ska oroa oss — och vems sak det är att lösa — drar isär oss. Den ena manar till öppenhet: dela ditt liv, tekniken är här ändå. Den andra till försiktighet: en bild av dig kan idag fås att göra vad du aldrig gjort. Krocken: ligger ansvaret hos den enskilda som delar, eller hos dem som bygger och tillåter verktygen — och hjälper det ens att vara försiktig när vem som helst kan skapa dig?',
"de-tre-nivaerna":'Vilken nivå man fruktar — och om vi ens nått dit — drar isär oss. Den ena oroar sig för superintelligensen, det som en dag kan överträffa oss på allt. Den andra påpekar att vi ännu inte byggt en maskin lika bred som en människa, och att fjärran faror kan skymma de närmaste. Krocken: ska vi planera för det som kanske kommer, eller vakta det som redan är här — och har vi råd att välja bort något av dem?',
"dum-modell-over-manniska":'Samma system, sett med helt olika ögon — ta ett kreditbeslut. Den ena litar på modellen: den hittar mönster i data som en handläggare aldrig hinner se. Den andra ryser: har den lärt sig att postnummer och ålder "förutsäger" risk, straffar den dig för var du bor och vem du är. Krocken: är ett mönster i datan ett skäl, eller en fördom klädd i matematik — och vem får överklaga när maskinen sagt nej?',
"ansvar-nar-tekniken-agerar":'När något går fel med tekniken pekar olika blickar åt olika håll. Den ena skyller på användaren: läs manualen, sköt ditt. Den andra på designen: en produkt som är lätt att använda fel är ofta illa byggd, inte illa använd. Krocken: ligger felet hos handen som gjorde det, eller hos den som gjorde felet lätt att göra — och vem bär ansvaret när ingen hand längre håller i?',
# --- 050 ---
"hur-borjar-jag":'Hur man bäst börjar drar isär oss — och det är helt okej. Den ena vill hoppa i och prova: man lär sig simma i vattnet, inte på land. Den andra vill läsa på först, förstå innan man klickar. Krocken: lär man sig ett nytt verktyg bäst genom att använda det eller genom att förstå det — och för vem gäller vilket?',
"funkar-det-i-vardagen":'Om AI gör verklig nytta i vardagen eller inte står folk på olika mark. Den ena avfärdar: det är bara en chattbot, en leksak som låter smart. Den andra ser ett verktyg som redan sparar timmar åt den som lärt sig var det passar. Krocken: skiljer sig "leksak" och "verktyg" åt i tekniken, eller i hur mycket möda man lagt på att lära sig den?',
"bygga-nagot-sjalv":'Hur man "borde" bygga är åsikterna många och högljudda om. Den ena vill jaga det senaste: nya verktyg, nya sätt, hela tiden. Den andra vill hålla grunden: förstå det du bygger på, så det håller när trenden vänt. Krocken: kommer man längst av att följa fronten eller av att behärska basen — och hur mycket nytt hinner man lära innan det man lärt är förlegat?',
# --- 060 ---
"privat-eller-foretag":'Alla vill komma igång — men hur mycket av andras förtroende man riskerar på vägen drar isär oss. Den ena väljer bekvämligheten: enklaste vägen in, reglerna sen. Den andra ser efterlevnaden först: matar man in andras uppgifter i fel tjänst kan man inte ta tillbaka det. Krocken: får smidigheten gå före ansvaret när det är någon annans data man förvaltar?',
"vad-far-jag-skriva-in":'Hur mycket man vågar mata in i en AI drar isär oss. Den ena delar generöst: ju mer den vet, desto bättre hjälper den. Den andra håller tätt: det du skriver in kan lagras, läras av, läcka. Krocken: var går gränsen mellan att bidra med det som gör verktyget bättre och att lämna ifrån sig det du inte får ta tillbaka?',
"foretagsklar-ai":'Hur man väljer en AI-tjänst drar isär oss. Den ena vill gå igenom kriterierna: avtal, dataskydd, var uppgifterna hamnar. Den andra litar på magkänslan: vi tar den alla andra tar. Krocken: är en checklista onödig byråkrati eller just det som skiljer ett tryggt val från ett man ångrar — och märker man skillnaden förrän det brustit?',
"vem-ager-det-jag-skapar":'Vem som äger det man skapar med AI drar isär oss — på flera sätt samtidigt. Den ena säger: min prompt, mitt verk. Den andra: maskinen gjorde jobbet, och den tränades på andras verk. Krocken: sitter upphovet i handen som bad om det, i verktyget som gjorde det, eller hos alla vars verk det byggdes av — och lagen själv är ännu inte överens?',
"ai-policy":'Hur en AI-policy borde se ut drar isär oss. Den ena vill förbjuda: säkrast att stänga av det man inte kontrollerar. Den andra vill möjliggöra: ett förbud föder bara skugg-användning, verktyg i smyg utan regler. Krocken: blir en organisation tryggast av att stänga dörren eller av att öppna den med ramar — och vilket förbud är det som faktiskt följs?',
# --- 070 ---
"vad-tar-jag-med-mig":'Vilken lärdom man väljer att bära härifrån drar isär oss — och det är helt i sin ordning. Den ena tar med sig hantverket: lär dig prompta, lär dig verktygen. Den andra tar med sig hållningen: lär dig fråga, tvivla, behålla omdömet. Krocken: är det knepen eller omdömet som består när verktygen bytts ut igen?',
"ordning-eller-kaos":'Var värdet i skapandet sitter drar isär oss. Den ena njuter av mängden: äntligen kan man generera hur mycket som helst. Den andra av gallringen: det svåra och värdefulla är att välja bort, att hitta det enda som håller. Krocken: ligger konsten i att skapa mycket eller i att välja rätt — och gör en maskin som ger oss oändligt mycket det första lättare och det andra svårare?',
"vad-ska-man-lara-sig":'Vad skolan och vi själva bör satsa på när maskinen kan slå upp allt drar isär oss. Den ena håller på grunderna: fakta och färdigheter måste sitta, annars kan man inte tänka. Den andra på det maskinen inte gör: att fråga, väga, känna, döma. Krocken: ska vi lära oss det maskinen redan kan, för att förstå det — eller det den inte kan, för att förbli behövda?',
}
SEC=re.compile(r'<div class="section">\s*<div class="section-head"><span class="num">(\d+)</span><span class="concept">Var vi krockar</span><span class="tag">([^<]*)</span></div>\s*<div class="body">.*?</div>\s*</div>(?=\s*(?:<hr>|<div class="section">|<div class="extra-head">|<div class="future-box">))', re.S)
def newsec(num,tag,prose):
    return '<div class="section">\n  <div class="section-head"><span class="num">%s</span><span class="concept">Var vi krockar</span><span class="tag">%s</span></div>\n  <div class="body">%s</div>\n</div>'%(num,tag,prose)
P=ROOT+"content/forklara-ai/manifest.js"; s=io.open(P,encoding="utf-8").read();PRE="window.LECTURE = "
i=s.index(PRE)+len(PRE);j=s.rfind(";");head,tail=s[:i],s[j:]
L=json.loads(s[i:j]);k={x["id"]:x for x in L["kort"]}
n=0
for kid,prose in K.items():
    f=k[kid]["fordjupning"]; m=SEC.search(f); assert m,"manifest %s"%kid
    k[kid]["fordjupning"]=f.replace(m.group(0), newsec(m.group(1),m.group(2),prose),1); n+=1
out=head+json.dumps(L,ensure_ascii=False,indent=2)+tail
json.loads(out[out.index(PRE)+len(PRE):out.rfind(";")]); io.open(P,"w",encoding="utf-8").write(out)
print("Föreläsning (verktyg): %d krockar omgjorda"%n)
print("KYR:",sum(1 for c in out if c in set('аеорсухіјѕАЕОРСТНКМВ')))
